-- Gives tag_categories the same alias vocabulary that tags already carry,
-- so competency-worded job descriptions can reach a technology-worded skill
-- inventory.
--
-- Context: a staff-level JD scored 0/100 technical with all nine required
-- skills reported as gaps, for capabilities the user demonstrably has. The
-- JD named no concrete technologies at all — it asked for "CI/CD",
-- "observability", "automated testing", "event-driven systems", "data
-- modeling". Extraction faithfully returned those phrases, and the scorer
-- compared them against skill tag *names* (Jenkins, Splunk, JUnit, Kafka,
-- PostgreSQL). No amount of string matching bridges "CI/CD" -> Jenkins:
-- the two sit at different levels of abstraction, and that is a taxonomy
-- problem, not a spelling problem.
--
-- Categories already sit at exactly the abstraction level JDs use — the
-- existing set includes "Tools & CI/CD", "Observability", and "Testing",
-- near-verbatim matches for the phrases above — but scoring never saw them.
-- Aliasing the category is what lets "data modeling" find the Databases
-- category and, through it, PostgreSQL and Cassandra.
--
-- This mirrors tags.aliases (migration 001) deliberately rather than
-- introducing a second mechanism. The vocabulary is user-owned data, editable
-- by SQL as new JD phrasings turn up, and stays out of Go constants.

ALTER TABLE tag_categories ADD COLUMN aliases TEXT[];
--
-- ---------------------------------------------------------------------------
-- The data statements that used to live here have moved to the seed files.
--
-- Migrations own structure; seeds own vocabulary. This one carried a software
-- competency thesaurus keyed by category name -- 'Observability', 'Testing',
-- 'Tools & CI/CD' -- which is one industry's taxonomy written into the applied
-- history of the repo, inherited by every user whether or not they have those
-- categories.
--
-- It was also the wrong place mechanically, which is what #74 was: a migration
-- cannot populate rows the seed has not created yet. On a fresh database these
-- UPDATEs ran before any category existed, matched zero rows, and left nine of
-- ten categories on NULL with the whole category matching layer inert.
--
-- Whoever creates a row populates its columns. database/sample/001_foundation.sql
-- and the private seed both carry this vocabulary in the same INSERT that
-- creates the category, and TestSampleSeedCarriesCategoryVocabulary is the
-- guard. Stripping it here changes nothing for a database that already ran it.
-- ---------------------------------------------------------------------------
