-- Restores the competency vocabulary migration 012 was supposed to seed.
--
-- 012 added tag_categories.aliases and populated it with one UPDATE per
-- category, so that a capability-worded JD could reach a technology-worded
-- skill inventory: "CI/CD" -> Jenkins, "observability" -> Splunk, "apis" ->
-- REST. In the live database nine of ten categories carried NULL, and the
-- whole third matching layer in internal/fitgate was therefore dead.
--
-- 012 did not fail. It ran against an empty table. Migrations run before
-- `make seed`, and the nine base categories are *created* afterward by
-- database/seed/001_foundation.sql, whose insert names only
-- (id, user_id, name, sort_order) and whose ON CONFLICT (id) DO UPDATE sets
-- only name and sort_order. The UPDATE matched zero rows and the seed never
-- supplied aliases, so the column was never written rather than written and
-- lost. 'AI & LLM' is the sole survivor because seed file 023 carries its
-- aliases inline in its own INSERT.
--
-- 012's comment anticipated a *naming* mismatch ("a user whose categories are
-- named differently gets no rows updated and no error"). The real hazard was
-- ordering, and it is not fixable inside 012: a migration cannot seed rows
-- that do not exist yet. This migration repairs existing databases; the
-- durable fix is that the seed files now carry the aliases themselves, so the
-- two stop disagreeing about who owns the column.
--
-- Symptom that surfaced it: a Senior Staff posting requiring "APIs" scored it
-- as a gap against a profile holding REST at expert, and the narrative told
-- the user they were missing API work. See #74.
--
-- COALESCE, not assignment. A category that already has aliases keeps them —
-- this must not clobber 'AI & LLM', and it must not overwrite vocabulary a
-- user has curated by hand since 012. It is idempotent and safe to re-run:
-- a second pass finds every target non-NULL and changes nothing.
--
-- A category alias names the *capability*, not a technology. Putting 'kafka'
-- here would grant the whole Protocols & Messaging category for one tool;
-- that belongs in tags.aliases on the Kafka row.

-- ---------------------------------------------------------------------------
-- The UPDATE statements that used to follow have moved to the seed files.
--
-- Migrations own structure; seeds own vocabulary. What was here was one
-- industry's taxonomy written into the applied history of a public repo, and
-- inherited by every user whether or not they hold those categories.
--
-- It was also the wrong place mechanically, which is the whole of #74: a
-- migration cannot populate rows the seed has not created yet. Whoever creates
-- a row populates its columns, so database/sample/001_foundation.sql and the
-- private seed both carry this vocabulary in the same INSERT that creates the
-- row it describes. TestSampleSeedCarriesCategoryVocabulary and
-- TestSampleSeedCarriesCrossCategoryTerms are the guards.
--
-- Stripping it here changes nothing for a database that already ran it, and a
-- fresh one gets the vocabulary from the seed a moment later.
-- ---------------------------------------------------------------------------
