-- Removes exactly the terms the up migration adds, leaving any other alias on
-- those tags untouched.
--
-- Unlike 018 this IS reversible, and for a specific reason: the terms are a
-- known, closed list, so a rollback can subtract them by name rather than
-- guessing which entries it put there. 018 backfilled a whole column where a
-- populated row is indistinguishable from one a user curated, which is what
-- made its down a no-op.
--
-- 'restful' and 'rest api' are deliberately not removed from REST — both
-- predate this migration (seed 013), and a down migration that deletes
-- vocabulary it did not add is how a rollback quietly costs you a match. The
-- up migration only adds 'rest api' where it is absent, so on a database that
-- already had it this is exactly symmetric; on one that did not, the term
-- survives the rollback. That asymmetry errs toward keeping a match.

-- ---------------------------------------------------------------------------
-- The UPDATE statements that used to follow have moved to the seed files.
--
-- Migrations own structure; seeds own vocabulary. What was here was one
-- industry's taxonomy written into the applied history of a public repo, and
-- inherited by every user whether or not they hold those categories.
--
-- It was also the wrong place mechanically, which is the whole of #74: a
-- migration cannot populate rows the seed has not created yet. Whoever creates
-- a row populates its columns, so database/sample/001_foundation.sql and the
-- private seed both carry this vocabulary in the same INSERT that creates the
-- row it describes. TestSampleSeedCarriesCategoryVocabulary and
-- TestSampleSeedCarriesCrossCategoryTerms are the guards.
--
-- Stripping it here changes nothing for a database that already ran it, and a
-- fresh one gets the vocabulary from the seed a moment later.
-- ---------------------------------------------------------------------------
