-- Sample data: Northbound Logistics contributions (2021-10 .. present)
--
-- FICTIONAL -- see database/sample/README.md.
--
-- Positions:
--   5b000000-...-05  Staff Software Engineer  (2021-10 .. 2024-02)
--   5b000000-...-06  Principal Engineer       (2024-02 .. present)

BEGIN;

INSERT INTO contributions (
  id, user_id, position_id, summary, full_description, outcomes, scale_context
) VALUES
  -- ---------- Staff Software Engineer ----------
  ('51000000-0000-0000-0000-000000000023', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Rebuilt the carrier telemetry ingest pipeline, scaling it from 40M to 900M events/day',
   'Every customer-facing shipment ETA depends on carrier GPS telemetry, and the ingest path was a single Python consumer group writing row-by-row into PostgreSQL that had already been vertically scaled as far as the instance class allowed. Rebuilt it in Go: partitioned by carrier with per-partition batching, deduplication against a Redis bloom filter before write, and TimescaleDB hypertables sized for the actual query pattern instead of the original naive schema. Ran old and new pipelines in parallel for six weeks comparing outputs event-for-event before cutting over.',
   'Ingest capacity went from about 40M to 900M events per day while per-event cost fell 62%. Ingest lag at peak dropped from as much as 40 minutes to under 20 seconds, which is what made "live" ETAs honest rather than aspirational.',
   'Roughly 300,000 tracked vehicles across 1,100 carrier integrations.'),

  ('51000000-0000-0000-0000-000000000024', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Designed the event schema registry and compatibility rules for the data platform',
   'Eleven teams published to Kafka with no schema governance, and a producer-side field rename had recently broken three downstream consumers silently, corrupting a day of ETA history before anyone noticed. Introduced a schema registry with enforced backward compatibility in CI, plus a written compatibility policy covering what producers may change unilaterally and what requires consumer coordination. The policy mattered more than the tooling: the registry only works if people agree what compatibility means.',
   'Schema-related consumer breakages went from roughly one a month to zero over the following 18 months. Onboarding a new consumer stopped requiring a conversation with the producing team.',
   '11 producing teams, 60+ topics, roughly 900M events per day.'),

  ('51000000-0000-0000-0000-000000000025', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Cut telemetry storage cost 62% with a tiered retention model',
   'Telemetry storage was the single largest line in the infrastructure budget and growing faster than revenue, because everything was retained at full resolution indefinitely. Worked with the product and data science teams to establish what query patterns actually needed full resolution, then built tiered retention: full fidelity for 30 days, downsampled aggregates to 2 years, cold object storage beyond. The engineering was straightforward; establishing what could be safely downsampled took most of the effort.',
   'Storage cost per tracked shipment fell 62% while every existing customer-facing query kept working unchanged. Payback on the engineering time was under two months.',
   'Roughly 340TB of hot telemetry at project start.'),

  ('51000000-0000-0000-0000-000000000026', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Built the shipment ETA prediction serving path',
   'The data science team had an ETA model that performed well offline but no path to production; predictions were being generated by a notebook on a schedule. Built the serving infrastructure: a feature pipeline reading from the telemetry stream, a gRPC prediction service with model versioning and shadow deployment, and monitoring on prediction drift rather than only on service health. Kept the model interface narrow so data scientists could ship new versions without an engineering handoff.',
   'Took ETA predictions from a daily batch to sub-second on-demand serving. Model iteration cycle went from about six weeks to under one, and mean absolute ETA error improved 23% in the first year purely from being able to iterate faster.',
   'Roughly 2.5M predictions per day across 40,000 active shipments.'),

  ('51000000-0000-0000-0000-000000000027', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Led incident response and the postmortem for a 9-hour ingest outage',
   'A carrier integration began sending timestamps in a different timezone after their own upgrade, which poisoned the deduplication index and silently stalled ingest for a third of tracked shipments. Was incident commander for the nine-hour response, including the call to serve stale-but-labeled ETAs rather than no ETAs while the backfill ran. Wrote the postmortem and drove the four follow-up items, the important one being input validation at the integration boundary rather than trusting partner data shape.',
   'Backfilled without permanent data loss. The validation work that came out of the postmortem caught 14 similar partner-side changes over the following year, each of which would previously have been an incident.',
   'Roughly 100,000 affected shipments across 380 enterprise customers.'),

  ('51000000-0000-0000-0000-000000000028', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000005',
   'Replaced hand-rolled search with Elasticsearch for shipment lookup',
   'Shipment search ran as a set of increasingly baroque SQL LIKE queries against the primary database, was slow, and could not handle the partial reference-number matching that support staff actually needed. Moved search to Elasticsearch with a Kafka-driven index, an analyzer tuned for freight reference formats (which are full of dashes and inconsistent padding), and a relevance model built by sitting with the support team and watching how they actually search.',
   'p95 search latency fell from about 3.4s to 120ms, and support ticket time-to-first-response improved 31%. Removed the largest remaining source of load on the primary database.',
   'Roughly 40M indexed shipments, 200,000 searches per day.'),

  -- ---------- Principal Engineer ----------
  ('51000000-0000-0000-0000-000000000029', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Leads the multi-region active-active program',
   'Enterprise customers in the EU began requiring both data residency and regional failover, which the single-region architecture could not provide. Owns the technical program: regional data partitioning with residency enforced at the storage layer, conflict-free replication for the genuinely global data, and an explicit written classification of every dataset as regional, global, or replicated. Deliberately sequenced residency first and failover second, because residency unblocked revenue while failover was insurance.',
   'EU region live with 12 enterprise customers migrated and two contracts closed that were explicitly blocked on residency. Failover phase on track for completion in the current quarter.',
   'Two regions live, roughly 60 services classified, 380 enterprise customers.'),

  ('51000000-0000-0000-0000-000000000030', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Chairs the architecture review process',
   'Architecture decisions were being made in scattered documents with no durable record of the reasoning, so the same debates recurred every 18 months with new participants. Established a lightweight review: a written ADR for decisions that are expensive to reverse, a standing review with a small rotating panel, and an explicit rule that review advises rather than approves, so it does not become a gate that teams route around.',
   'Roughly 40 ADRs recorded in the first 18 months. The measurable win is that the recurring debates stopped recurring; new engineers now read the history instead of relitigating it.',
   'Engineering org of roughly 120 across 14 teams.'),

  ('51000000-0000-0000-0000-000000000031', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Built the engineering mentorship track and career framework for senior+ ICs',
   'The company had no articulated path above senior IC, so the only visible route to more scope was management, and two strong senior engineers had already left over it. Wrote the staff and principal levels of the career framework with concrete behavioral examples rather than adjectives, and built a mentorship track pairing senior engineers with staff+ mentors on scoped, real technical stretch work.',
   'Six engineers promoted to staff through the track in two years. Senior IC attrition fell from about 18% to 7% annually.',
   'Roughly 120 engineers, 30 at senior level or above.'),

  ('51000000-0000-0000-0000-000000000032', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Drove the platform-wide migration from REST to gRPC for internal traffic',
   'Internal service-to-service calls were JSON over HTTP with hand-written clients, inconsistent error semantics, and no shared contract, which made cross-team debugging unusually painful. Led the migration to gRPC with a shared protobuf repository and generated clients. Kept REST at the public edge, on the reasoning that gRPC''s benefits are internal and forcing it on external consumers would trade a real cost for an imagined one.',
   'Internal p99 call latency fell 34% and payload sizes roughly 60%. The generated-client change eliminated a recurring class of bug where two teams disagreed about a field''s nullability.',
   'Roughly 60 services, 14 teams, migration 80% complete.'),

  ('51000000-0000-0000-0000-000000000033', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Designed the carrier integration framework that cut new-integration time 80%',
   'Every new carrier telemetry integration was bespoke code, and with 1,100 integrations the marginal cost of the next one had become the binding constraint on customer onboarding. Designed a declarative integration framework: partner-specific transport, authentication, and field mapping expressed as configuration against a normalized internal telemetry model, with a conformance test suite a partner can run themselves before certification.',
   'New carrier integration time fell from about three weeks to three days, and roughly 60% of new integrations now complete with no engineering involvement at all. Customer onboarding stopped being gated on integration engineering capacity.',
   '1,100 existing carrier integrations; 140 onboarded through the framework to date.'),

  ('51000000-0000-0000-0000-000000000034', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Introduced continuous load testing against a production-shaped environment',
   'Capacity problems were consistently discovered during peak season rather than before it, because load testing was a manual exercise run shortly before a known event. Built continuous load testing: a traffic model derived from real production patterns, replayed nightly against a production-shaped environment, with results tracked as a trend so regressions surface as a gradual slope rather than a cliff during Black Friday.',
   'Caught four capacity regressions before production over the following year, two of which would have been peak-season incidents based on the projected traffic curve. Peak season passed without a capacity-caused incident for the first time in company history.',
   'Peak season traffic roughly 3.5x baseline, about 900M events per day at normal load.'),

  ('51000000-0000-0000-0000-000000000035', '5a000000-0000-0000-0000-000000000001',
   '5b000000-0000-0000-0000-000000000006',
   'Wrote the internal Go style guide and service design handbook',
   'Code review across 14 teams kept relitigating the same stylistic and structural questions, which was slow and made review feel arbitrary to newer engineers. Wrote a style guide and service design handbook that documented the decisions rather than the preferences, with the rationale attached to each so a rule could be argued with on its merits. Explicitly marked which rules were enforced by tooling and which were advisory.',
   'Recurring style debates largely disappeared from review, and review turnaround improved about 25%. The handbook became standard reading in engineering onboarding.',
   'Roughly 120 engineers, 60 Go services.')

ON CONFLICT (id) DO UPDATE SET
  summary          = EXCLUDED.summary,
  full_description = EXCLUDED.full_description,
  outcomes         = EXCLUDED.outcomes,
  scale_context    = EXCLUDED.scale_context,
  updated_at       = now();

-- ============================================================
-- Contribution tags
-- ============================================================
INSERT INTO contribution_tags (contribution_id, tag_id) VALUES
  -- 023 telemetry ingest rebuild: Go, Python, Kafka, TimescaleDB, Redis, Distributed Systems, EDA
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000002'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000040'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000034'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000031'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000070'),
  ('51000000-0000-0000-0000-000000000023', '57000000-0000-0000-0000-000000000071'),

  -- 024 schema registry: Kafka, EDA, Distributed Systems, Technical Leadership
  ('51000000-0000-0000-0000-000000000024', '57000000-0000-0000-0000-000000000040'),
  ('51000000-0000-0000-0000-000000000024', '57000000-0000-0000-0000-000000000071'),
  ('51000000-0000-0000-0000-000000000024', '57000000-0000-0000-0000-000000000070'),
  ('51000000-0000-0000-0000-000000000024', '57000000-0000-0000-0000-000000000075'),

  -- 025 tiered retention: TimescaleDB, PostgreSQL, AWS, SQL
  ('51000000-0000-0000-0000-000000000025', '57000000-0000-0000-0000-000000000034'),
  ('51000000-0000-0000-0000-000000000025', '57000000-0000-0000-0000-000000000030'),
  ('51000000-0000-0000-0000-000000000025', '57000000-0000-0000-0000-000000000020'),
  ('51000000-0000-0000-0000-000000000025', '57000000-0000-0000-0000-000000000004'),

  -- 026 ETA serving: Go, Python, gRPC, Kafka, OpenTelemetry
  ('51000000-0000-0000-0000-000000000026', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000026', '57000000-0000-0000-0000-000000000002'),
  ('51000000-0000-0000-0000-000000000026', '57000000-0000-0000-0000-000000000041'),
  ('51000000-0000-0000-0000-000000000026', '57000000-0000-0000-0000-000000000040'),
  ('51000000-0000-0000-0000-000000000026', '57000000-0000-0000-0000-000000000062'),

  -- 027 ingest outage: Incident Response, Kafka, Redis, Technical Leadership
  ('51000000-0000-0000-0000-000000000027', '57000000-0000-0000-0000-000000000073'),
  ('51000000-0000-0000-0000-000000000027', '57000000-0000-0000-0000-000000000040'),
  ('51000000-0000-0000-0000-000000000027', '57000000-0000-0000-0000-000000000031'),
  ('51000000-0000-0000-0000-000000000027', '57000000-0000-0000-0000-000000000075'),

  -- 028 Elasticsearch search: Elasticsearch, Kafka, Go, PostgreSQL
  ('51000000-0000-0000-0000-000000000028', '57000000-0000-0000-0000-000000000033'),
  ('51000000-0000-0000-0000-000000000028', '57000000-0000-0000-0000-000000000040'),
  ('51000000-0000-0000-0000-000000000028', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000028', '57000000-0000-0000-0000-000000000030'),

  -- 029 multi-region: Distributed Systems, AWS, Kubernetes, Terraform, PostgreSQL, Technical Leadership
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000070'),
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000020'),
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000021'),
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000022'),
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000030'),
  ('51000000-0000-0000-0000-000000000029', '57000000-0000-0000-0000-000000000075'),

  -- 030 architecture review: Technical Leadership, DDD, Distributed Systems
  ('51000000-0000-0000-0000-000000000030', '57000000-0000-0000-0000-000000000075'),
  ('51000000-0000-0000-0000-000000000030', '57000000-0000-0000-0000-000000000072'),
  ('51000000-0000-0000-0000-000000000030', '57000000-0000-0000-0000-000000000070'),

  -- 031 mentorship track: Mentoring, Technical Leadership
  ('51000000-0000-0000-0000-000000000031', '57000000-0000-0000-0000-000000000074'),
  ('51000000-0000-0000-0000-000000000031', '57000000-0000-0000-0000-000000000075'),

  -- 032 REST -> gRPC: gRPC, REST, Go, Distributed Systems, Technical Leadership
  ('51000000-0000-0000-0000-000000000032', '57000000-0000-0000-0000-000000000041'),
  ('51000000-0000-0000-0000-000000000032', '57000000-0000-0000-0000-000000000042'),
  ('51000000-0000-0000-0000-000000000032', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000032', '57000000-0000-0000-0000-000000000070'),
  ('51000000-0000-0000-0000-000000000032', '57000000-0000-0000-0000-000000000075'),

  -- 033 integration framework: Go, EDI, REST, Contract Testing, DDD
  ('51000000-0000-0000-0000-000000000033', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000033', '57000000-0000-0000-0000-000000000043'),
  ('51000000-0000-0000-0000-000000000033', '57000000-0000-0000-0000-000000000042'),
  ('51000000-0000-0000-0000-000000000033', '57000000-0000-0000-0000-000000000052'),
  ('51000000-0000-0000-0000-000000000033', '57000000-0000-0000-0000-000000000072'),

  -- 034 continuous load testing: Load Testing, Kubernetes, Prometheus, Grafana, GitHub Actions
  ('51000000-0000-0000-0000-000000000034', '57000000-0000-0000-0000-000000000051'),
  ('51000000-0000-0000-0000-000000000034', '57000000-0000-0000-0000-000000000021'),
  ('51000000-0000-0000-0000-000000000034', '57000000-0000-0000-0000-000000000060'),
  ('51000000-0000-0000-0000-000000000034', '57000000-0000-0000-0000-000000000061'),
  ('51000000-0000-0000-0000-000000000034', '57000000-0000-0000-0000-000000000080'),

  -- 035 style guide: Go, Technical Leadership, Mentoring, DDD
  ('51000000-0000-0000-0000-000000000035', '57000000-0000-0000-0000-000000000001'),
  ('51000000-0000-0000-0000-000000000035', '57000000-0000-0000-0000-000000000075'),
  ('51000000-0000-0000-0000-000000000035', '57000000-0000-0000-0000-000000000074'),
  ('51000000-0000-0000-0000-000000000035', '57000000-0000-0000-0000-000000000072')

ON CONFLICT (contribution_id, tag_id) DO NOTHING;

COMMIT;
