// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"encoding/json"

	json "encoding/json"
	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    user_id, company_name, role_title, jd_url, jd_text, status, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, company_name, role_title, jd_url, jd_text, jd_signals, status, applied_on, notes, created_at, updated_at
`

type CreateApplicationParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CompanyName string    `json:"company_name"`
	RoleTitle   string    `json:"role_title"`
	JdUrl       *string   `json:"jd_url"`
	JdText      *string   `json:"jd_text"`
	Status      string    `json:"status"`
	Notes       *string   `json:"notes"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.CompanyName,
		arg.RoleTitle,
		arg.JdUrl,
		arg.JdText,
		arg.Status,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.RoleTitle,
		&i.JdUrl,
		&i.JdText,
		&i.JdSignals,
		&i.Status,
		&i.AppliedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, user_id, company_name, role_title, jd_url, jd_text, jd_signals, status, applied_on, notes, created_at, updated_at FROM applications
WHERE id = $1 AND user_id = $2
`

type GetApplicationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.RoleTitle,
		&i.JdUrl,
		&i.JdText,
		&i.JdSignals,
		&i.Status,
		&i.AppliedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, user_id, company_name, role_title, jd_url, jd_text, jd_signals, status, applied_on, notes, created_at, updated_at FROM applications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApplications(ctx context.Context, userID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.RoleTitle,
			&i.JdUrl,
			&i.JdText,
			&i.JdSignals,
			&i.Status,
			&i.AppliedOn,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET company_name = $3,
    role_title   = $4,
    jd_url       = $5,
    jd_text      = $6,
    status       = $7,
    notes        = $8,
    updated_at   = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, company_name, role_title, jd_url, jd_text, jd_signals, status, applied_on, notes, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	CompanyName string    `json:"company_name"`
	RoleTitle   string    `json:"role_title"`
	JdUrl       *string   `json:"jd_url"`
	JdText      *string   `json:"jd_text"`
	Status      string    `json:"status"`
	Notes       *string   `json:"notes"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.UserID,
		arg.CompanyName,
		arg.RoleTitle,
		arg.JdUrl,
		arg.JdText,
		arg.Status,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.RoleTitle,
		&i.JdUrl,
		&i.JdText,
		&i.JdSignals,
		&i.Status,
		&i.AppliedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationSignals = `-- name: UpdateApplicationSignals :one
UPDATE applications
SET jd_signals = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, company_name, role_title, jd_url, jd_text, jd_signals, status, applied_on, notes, created_at, updated_at
`

type UpdateApplicationSignalsParams struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	JdSignals *json.RawMessage `json:"jd_signals"`
}

func (q *Queries) UpdateApplicationSignals(ctx context.Context, arg UpdateApplicationSignalsParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationSignals, arg.ID, arg.UserID, arg.JdSignals)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.RoleTitle,
		&i.JdUrl,
		&i.JdText,
		&i.JdSignals,
		&i.Status,
		&i.AppliedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
