// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contributions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getContribution = `-- name: GetContribution :one
SELECT id, user_id, position_id, summary, full_description, outcomes, scale_context, is_active, created_at, updated_at FROM contributions
WHERE id = $1 AND user_id = $2
`

type GetContributionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContribution(ctx context.Context, arg GetContributionParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContribution, arg.ID, arg.UserID)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PositionID,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionsByPosition = `-- name: GetContributionsByPosition :many
SELECT id, user_id, position_id, summary, full_description, outcomes, scale_context, is_active, created_at, updated_at FROM contributions
WHERE position_id = $1 AND user_id = $2
ORDER BY created_at
`

type GetContributionsByPositionParams struct {
	PositionID uuid.UUID `json:"position_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContributionsByPosition(ctx context.Context, arg GetContributionsByPositionParams) ([]Contribution, error) {
	rows, err := q.db.Query(ctx, getContributionsByPosition, arg.PositionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contribution
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PositionID,
			&i.Summary,
			&i.FullDescription,
			&i.Outcomes,
			&i.ScaleContext,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
