// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contribution_drafts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countContributionDraftsByBatch = `-- name: CountContributionDraftsByBatch :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status = 'pending')  AS pending,
    COUNT(*) FILTER (WHERE status = 'approved') AS approved,
    COUNT(*) FILTER (WHERE status = 'rejected') AS rejected
FROM contribution_drafts
WHERE batch_id = $1 AND user_id = $2
`

type CountContributionDraftsByBatchParams struct {
	BatchID uuid.UUID `json:"batch_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type CountContributionDraftsByBatchRow struct {
	Total    int64 `json:"total"`
	Pending  int64 `json:"pending"`
	Approved int64 `json:"approved"`
	Rejected int64 `json:"rejected"`
}

func (q *Queries) CountContributionDraftsByBatch(ctx context.Context, arg CountContributionDraftsByBatchParams) (CountContributionDraftsByBatchRow, error) {
	row := q.db.QueryRow(ctx, countContributionDraftsByBatch, arg.BatchID, arg.UserID)
	var i CountContributionDraftsByBatchRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Approved,
		&i.Rejected,
	)
	return i, err
}

const createContributionDraft = `-- name: CreateContributionDraft :one
INSERT INTO contribution_drafts (
    id, user_id, batch_id, employer_name, position_title,
    summary, full_description, outcomes, scale_context
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags
`

type CreateContributionDraftParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	BatchID         uuid.UUID `json:"batch_id"`
	EmployerName    string    `json:"employer_name"`
	PositionTitle   string    `json:"position_title"`
	Summary         *string   `json:"summary"`
	FullDescription *string   `json:"full_description"`
	Outcomes        *string   `json:"outcomes"`
	ScaleContext    *string   `json:"scale_context"`
}

func (q *Queries) CreateContributionDraft(ctx context.Context, arg CreateContributionDraftParams) (ContributionDraft, error) {
	row := q.db.QueryRow(ctx, createContributionDraft,
		arg.ID,
		arg.UserID,
		arg.BatchID,
		arg.EmployerName,
		arg.PositionTitle,
		arg.Summary,
		arg.FullDescription,
		arg.Outcomes,
		arg.ScaleContext,
	)
	var i ContributionDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.EmployerName,
		&i.PositionTitle,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedTags,
	)
	return i, err
}

const getContributionDraft = `-- name: GetContributionDraft :one
SELECT id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags FROM contribution_drafts
WHERE id = $1 AND user_id = $2
`

type GetContributionDraftParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContributionDraft(ctx context.Context, arg GetContributionDraftParams) (ContributionDraft, error) {
	row := q.db.QueryRow(ctx, getContributionDraft, arg.ID, arg.UserID)
	var i ContributionDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.EmployerName,
		&i.PositionTitle,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedTags,
	)
	return i, err
}

const listContributionDraftsByBatch = `-- name: ListContributionDraftsByBatch :many
SELECT id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags FROM contribution_drafts
WHERE batch_id = $1 AND user_id = $2
ORDER BY created_at
`

type ListContributionDraftsByBatchParams struct {
	BatchID uuid.UUID `json:"batch_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ListContributionDraftsByBatch(ctx context.Context, arg ListContributionDraftsByBatchParams) ([]ContributionDraft, error) {
	rows, err := q.db.Query(ctx, listContributionDraftsByBatch, arg.BatchID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionDraft
	for rows.Next() {
		var i ContributionDraft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BatchID,
			&i.EmployerName,
			&i.PositionTitle,
			&i.Summary,
			&i.FullDescription,
			&i.Outcomes,
			&i.ScaleContext,
			&i.Flags,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContributionDraft = `-- name: UpdateContributionDraft :one
UPDATE contribution_drafts
SET summary          = $3,
    full_description  = $4,
    outcomes          = $5,
    scale_context     = $6,
    flags             = $7,
    updated_at        = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags
`

type UpdateContributionDraftParams struct {
	ID              uuid.UUID        `json:"id"`
	UserID          uuid.UUID        `json:"user_id"`
	Summary         *string          `json:"summary"`
	FullDescription *string          `json:"full_description"`
	Outcomes        *string          `json:"outcomes"`
	ScaleContext    *string          `json:"scale_context"`
	Flags           *json.RawMessage `json:"flags"`
}

func (q *Queries) UpdateContributionDraft(ctx context.Context, arg UpdateContributionDraftParams) (ContributionDraft, error) {
	row := q.db.QueryRow(ctx, updateContributionDraft,
		arg.ID,
		arg.UserID,
		arg.Summary,
		arg.FullDescription,
		arg.Outcomes,
		arg.ScaleContext,
		arg.Flags,
	)
	var i ContributionDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.EmployerName,
		&i.PositionTitle,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedTags,
	)
	return i, err
}

const updateContributionDraftEnrichment = `-- name: UpdateContributionDraftEnrichment :one
UPDATE contribution_drafts
SET flags          = $3,
    suggested_tags = $4,
    updated_at     = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags
`

type UpdateContributionDraftEnrichmentParams struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	Flags         *json.RawMessage `json:"flags"`
	SuggestedTags *json.RawMessage `json:"suggested_tags"`
}

// Stage 0b writes only its own outputs: the review flags and the tag
// suggestions. UpdateContributionDraft above also rewrites summary /
// full_description / outcomes / scale_context, which enrichment only ever
// echoes back unchanged.
func (q *Queries) UpdateContributionDraftEnrichment(ctx context.Context, arg UpdateContributionDraftEnrichmentParams) (ContributionDraft, error) {
	row := q.db.QueryRow(ctx, updateContributionDraftEnrichment,
		arg.ID,
		arg.UserID,
		arg.Flags,
		arg.SuggestedTags,
	)
	var i ContributionDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.EmployerName,
		&i.PositionTitle,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedTags,
	)
	return i, err
}

const updateContributionDraftStatus = `-- name: UpdateContributionDraftStatus :one
UPDATE contribution_drafts
SET status     = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, employer_name, position_title, summary, full_description, outcomes, scale_context, flags, status, created_at, updated_at, suggested_tags
`

type UpdateContributionDraftStatusParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateContributionDraftStatus(ctx context.Context, arg UpdateContributionDraftStatusParams) (ContributionDraft, error) {
	row := q.db.QueryRow(ctx, updateContributionDraftStatus, arg.ID, arg.UserID, arg.Status)
	var i ContributionDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.EmployerName,
		&i.PositionTitle,
		&i.Summary,
		&i.FullDescription,
		&i.Outcomes,
		&i.ScaleContext,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedTags,
	)
	return i, err
}
