// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCredentials = `-- name: GetCredentials :many
SELECT id, user_id, name, issuer, issued_on, expires_on, credential_url, created_at, updated_at FROM credentials
WHERE user_id = $1
ORDER BY issued_on DESC NULLS FIRST
`

func (q *Queries) GetCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, getCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Issuer,
			&i.IssuedOn,
			&i.ExpiresOn,
			&i.CredentialUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
