// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: education.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEducation = `-- name: GetEducation :many
SELECT id, user_id, institution, degree, field_of_study, started_on, ended_on, notes, created_at, updated_at FROM education
WHERE user_id = $1
ORDER BY ended_on DESC NULLS FIRST
`

func (q *Queries) GetEducation(ctx context.Context, userID uuid.UUID) ([]Education, error) {
	rows, err := q.db.Query(ctx, getEducation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Education
	for rows.Next() {
		var i Education
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Institution,
			&i.Degree,
			&i.FieldOfStudy,
			&i.StartedOn,
			&i.EndedOn,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
