// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEmployer = `-- name: GetEmployer :one
SELECT id, user_id, name, industry, notes, created_at, updated_at FROM employers
WHERE id = $1 AND user_id = $2
`

type GetEmployerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEmployer(ctx context.Context, arg GetEmployerParams) (Employer, error) {
	row := q.db.QueryRow(ctx, getEmployer, arg.ID, arg.UserID)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployers = `-- name: GetEmployers :many
SELECT id, user_id, name, industry, notes, created_at, updated_at FROM employers
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) GetEmployers(ctx context.Context, userID uuid.UUID) ([]Employer, error) {
	rows, err := q.db.Query(ctx, getEmployers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employer
	for rows.Next() {
		var i Employer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Industry,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
