// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_drafts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEntityDraft = `-- name: CreateEntityDraft :one
INSERT INTO entity_drafts (
    id, user_id, batch_id, kind, payload, depends_on, flags, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at
`

type CreateEntityDraftParams struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	BatchID   uuid.UUID        `json:"batch_id"`
	Kind      string           `json:"kind"`
	Payload   *json.RawMessage `json:"payload"`
	DependsOn []uuid.UUID      `json:"depends_on"`
	Flags     *json.RawMessage `json:"flags"`
	Status    string           `json:"status"`
}

func (q *Queries) CreateEntityDraft(ctx context.Context, arg CreateEntityDraftParams) (EntityDraft, error) {
	row := q.db.QueryRow(ctx, createEntityDraft,
		arg.ID,
		arg.UserID,
		arg.BatchID,
		arg.Kind,
		arg.Payload,
		arg.DependsOn,
		arg.Flags,
		arg.Status,
	)
	var i EntityDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Kind,
		&i.Payload,
		&i.DependsOn,
		&i.ResolvedID,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityDraft = `-- name: GetEntityDraft :one
SELECT id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at FROM entity_drafts
WHERE id = $1 AND user_id = $2
`

type GetEntityDraftParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEntityDraft(ctx context.Context, arg GetEntityDraftParams) (EntityDraft, error) {
	row := q.db.QueryRow(ctx, getEntityDraft, arg.ID, arg.UserID)
	var i EntityDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Kind,
		&i.Payload,
		&i.DependsOn,
		&i.ResolvedID,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntityDraftsByBatch = `-- name: ListEntityDraftsByBatch :many
SELECT id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at FROM entity_drafts
WHERE batch_id = $1 AND user_id = $2
ORDER BY created_at, id
`

type ListEntityDraftsByBatchParams struct {
	BatchID uuid.UUID `json:"batch_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Every draft in the batch, pending and resolved alike.
//
// The resolver needs the resolved ones: a dependent draft finds its parent's
// real id through resolved_id, and filtering them out here would make a
// second approval pass unable to see what the first one created.
func (q *Queries) ListEntityDraftsByBatch(ctx context.Context, arg ListEntityDraftsByBatchParams) ([]EntityDraft, error) {
	rows, err := q.db.Query(ctx, listEntityDraftsByBatch, arg.BatchID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityDraft
	for rows.Next() {
		var i EntityDraft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BatchID,
			&i.Kind,
			&i.Payload,
			&i.DependsOn,
			&i.ResolvedID,
			&i.Flags,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntityDraftRejected = `-- name: MarkEntityDraftRejected :one
UPDATE entity_drafts
SET status = 'rejected', updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at
`

type MarkEntityDraftRejectedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkEntityDraftRejected(ctx context.Context, arg MarkEntityDraftRejectedParams) (EntityDraft, error) {
	row := q.db.QueryRow(ctx, markEntityDraftRejected, arg.ID, arg.UserID)
	var i EntityDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Kind,
		&i.Payload,
		&i.DependsOn,
		&i.ResolvedID,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEntityDraftResolved = `-- name: MarkEntityDraftResolved :one
UPDATE entity_drafts
SET status = 'approved', resolved_id = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at
`

type MarkEntityDraftResolvedParams struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	ResolvedID *uuid.UUID `json:"resolved_id"`
}

func (q *Queries) MarkEntityDraftResolved(ctx context.Context, arg MarkEntityDraftResolvedParams) (EntityDraft, error) {
	row := q.db.QueryRow(ctx, markEntityDraftResolved, arg.ID, arg.UserID, arg.ResolvedID)
	var i EntityDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Kind,
		&i.Payload,
		&i.DependsOn,
		&i.ResolvedID,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEntityDraftFlags = `-- name: SetEntityDraftFlags :one
UPDATE entity_drafts
SET flags = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, batch_id, kind, payload, depends_on, resolved_id, flags, status, created_at, updated_at
`

type SetEntityDraftFlagsParams struct {
	ID     uuid.UUID        `json:"id"`
	UserID uuid.UUID        `json:"user_id"`
	Flags  *json.RawMessage `json:"flags"`
}

func (q *Queries) SetEntityDraftFlags(ctx context.Context, arg SetEntityDraftFlagsParams) (EntityDraft, error) {
	row := q.db.QueryRow(ctx, setEntityDraftFlags, arg.ID, arg.UserID, arg.Flags)
	var i EntityDraft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BatchID,
		&i.Kind,
		&i.Payload,
		&i.DependsOn,
		&i.ResolvedID,
		&i.Flags,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
