// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fit_reports.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFitReport = `-- name: CreateFitReport :one
INSERT INTO fit_reports (
    id, user_id, application_id, dealbreakers_clear, dealbreaker_hits,
    capability_score, capability_gaps, preference_gaps, narrative,
    preference_conflicts, screening_summary, capability_matches, preference_matches,
    capability_partial
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, user_id, application_id, dealbreakers_clear, dealbreaker_hits, capability_score, capability_gaps, preference_gaps, narrative, created_at, preference_conflicts, screening_summary, capability_matches, preference_matches, capability_partial
`

type CreateFitReportParams struct {
	ID                  uuid.UUID        `json:"id"`
	UserID              uuid.UUID        `json:"user_id"`
	ApplicationID       *uuid.UUID       `json:"application_id"`
	DealbreakersClear   bool             `json:"dealbreakers_clear"`
	DealbreakerHits     *json.RawMessage `json:"dealbreaker_hits"`
	CapabilityScore     pgtype.Numeric   `json:"capability_score"`
	CapabilityGaps      *json.RawMessage `json:"capability_gaps"`
	PreferenceGaps      *json.RawMessage `json:"preference_gaps"`
	Narrative           *string          `json:"narrative"`
	PreferenceConflicts *json.RawMessage `json:"preference_conflicts"`
	ScreeningSummary    *json.RawMessage `json:"screening_summary"`
	CapabilityMatches   *json.RawMessage `json:"capability_matches"`
	PreferenceMatches   *json.RawMessage `json:"preference_matches"`
	CapabilityPartial   *json.RawMessage `json:"capability_partial"`
}

func (q *Queries) CreateFitReport(ctx context.Context, arg CreateFitReportParams) (FitReport, error) {
	row := q.db.QueryRow(ctx, createFitReport,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.DealbreakersClear,
		arg.DealbreakerHits,
		arg.CapabilityScore,
		arg.CapabilityGaps,
		arg.PreferenceGaps,
		arg.Narrative,
		arg.PreferenceConflicts,
		arg.ScreeningSummary,
		arg.CapabilityMatches,
		arg.PreferenceMatches,
		arg.CapabilityPartial,
	)
	var i FitReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.DealbreakersClear,
		&i.DealbreakerHits,
		&i.CapabilityScore,
		&i.CapabilityGaps,
		&i.PreferenceGaps,
		&i.Narrative,
		&i.CreatedAt,
		&i.PreferenceConflicts,
		&i.ScreeningSummary,
		&i.CapabilityMatches,
		&i.PreferenceMatches,
		&i.CapabilityPartial,
	)
	return i, err
}

const getFitReport = `-- name: GetFitReport :one
SELECT id, user_id, application_id, dealbreakers_clear, dealbreaker_hits, capability_score, capability_gaps, preference_gaps, narrative, created_at, preference_conflicts, screening_summary, capability_matches, preference_matches, capability_partial FROM fit_reports
WHERE id = $1 AND user_id = $2
`

type GetFitReportParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFitReport(ctx context.Context, arg GetFitReportParams) (FitReport, error) {
	row := q.db.QueryRow(ctx, getFitReport, arg.ID, arg.UserID)
	var i FitReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.DealbreakersClear,
		&i.DealbreakerHits,
		&i.CapabilityScore,
		&i.CapabilityGaps,
		&i.PreferenceGaps,
		&i.Narrative,
		&i.CreatedAt,
		&i.PreferenceConflicts,
		&i.ScreeningSummary,
		&i.CapabilityMatches,
		&i.PreferenceMatches,
		&i.CapabilityPartial,
	)
	return i, err
}

const listFitReports = `-- name: ListFitReports :many
SELECT id, user_id, application_id, dealbreakers_clear, dealbreaker_hits, capability_score, capability_gaps, preference_gaps, narrative, created_at, preference_conflicts, screening_summary, capability_matches, preference_matches, capability_partial FROM fit_reports
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFitReports(ctx context.Context, userID uuid.UUID) ([]FitReport, error) {
	rows, err := q.db.Query(ctx, listFitReports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FitReport
	for rows.Next() {
		var i FitReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.DealbreakersClear,
			&i.DealbreakerHits,
			&i.CapabilityScore,
			&i.CapabilityGaps,
			&i.PreferenceGaps,
			&i.Narrative,
			&i.CreatedAt,
			&i.PreferenceConflicts,
			&i.ScreeningSummary,
			&i.CapabilityMatches,
			&i.PreferenceMatches,
			&i.CapabilityPartial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFitReportsByApplication = `-- name: ListFitReportsByApplication :many
SELECT id, user_id, application_id, dealbreakers_clear, dealbreaker_hits, capability_score, capability_gaps, preference_gaps, narrative, created_at, preference_conflicts, screening_summary, capability_matches, preference_matches, capability_partial FROM fit_reports
WHERE application_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListFitReportsByApplicationParams struct {
	ApplicationID *uuid.UUID `json:"application_id"`
	UserID        uuid.UUID  `json:"user_id"`
}

func (q *Queries) ListFitReportsByApplication(ctx context.Context, arg ListFitReportsByApplicationParams) ([]FitReport, error) {
	rows, err := q.db.Query(ctx, listFitReportsByApplication, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FitReport
	for rows.Next() {
		var i FitReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.DealbreakersClear,
			&i.DealbreakerHits,
			&i.CapabilityScore,
			&i.CapabilityGaps,
			&i.PreferenceGaps,
			&i.Narrative,
			&i.CreatedAt,
			&i.PreferenceConflicts,
			&i.ScreeningSummary,
			&i.CapabilityMatches,
			&i.PreferenceMatches,
			&i.CapabilityPartial,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
