// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_batches.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (id, user_id, raw_text, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, raw_text, status, error_text, created_at, updated_at
`

type CreateImportBatchParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	RawText string    `json:"raw_text"`
	Status  string    `json:"status"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.UserID,
		arg.RawText,
		arg.Status,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.Status,
		&i.ErrorText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, user_id, raw_text, status, error_text, created_at, updated_at FROM import_batches
WHERE id = $1 AND user_id = $2
`

type GetImportBatchParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetImportBatch(ctx context.Context, arg GetImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, arg.ID, arg.UserID)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.Status,
		&i.ErrorText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT id, user_id, raw_text, status, error_text, created_at, updated_at FROM import_batches
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListImportBatches(ctx context.Context, userID uuid.UUID) ([]ImportBatch, error) {
	rows, err := q.db.Query(ctx, listImportBatches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportBatch
	for rows.Next() {
		var i ImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.Status,
			&i.ErrorText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :one
UPDATE import_batches
SET status     = $3,
    error_text = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, raw_text, status, error_text, created_at, updated_at
`

type UpdateImportBatchStatusParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
	ErrorText *string   `json:"error_text"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStatus,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.ErrorText,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.Status,
		&i.ErrorText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
