// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: levels.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCareerLevel = `-- name: CreateCareerLevel :one
INSERT INTO career_levels (
    id, user_id, value, label, rank, aliases,
    length_budget, framing_guidance, is_fallback, source, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, value, label, rank, aliases, length_budget, framing_guidance, is_fallback, source, sort_order, created_at, updated_at
`

type CreateCareerLevelParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	Value           string    `json:"value"`
	Label           string    `json:"label"`
	Rank            int32     `json:"rank"`
	Aliases         []string  `json:"aliases"`
	LengthBudget    string    `json:"length_budget"`
	FramingGuidance string    `json:"framing_guidance"`
	IsFallback      bool      `json:"is_fallback"`
	Source          string    `json:"source"`
	SortOrder       int32     `json:"sort_order"`
}

func (q *Queries) CreateCareerLevel(ctx context.Context, arg CreateCareerLevelParams) (CareerLevel, error) {
	row := q.db.QueryRow(ctx, createCareerLevel,
		arg.ID,
		arg.UserID,
		arg.Value,
		arg.Label,
		arg.Rank,
		arg.Aliases,
		arg.LengthBudget,
		arg.FramingGuidance,
		arg.IsFallback,
		arg.Source,
		arg.SortOrder,
	)
	var i CareerLevel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Value,
		&i.Label,
		&i.Rank,
		&i.Aliases,
		&i.LengthBudget,
		&i.FramingGuidance,
		&i.IsFallback,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProficiencyLevel = `-- name: CreateProficiencyLevel :one
INSERT INTO proficiency_levels (
    id, user_id, value, label, rank, aliases, source, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, value, label, rank, aliases, source, sort_order, created_at, updated_at
`

type CreateProficiencyLevelParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Value     string    `json:"value"`
	Label     string    `json:"label"`
	Rank      int32     `json:"rank"`
	Aliases   []string  `json:"aliases"`
	Source    string    `json:"source"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateProficiencyLevel(ctx context.Context, arg CreateProficiencyLevelParams) (ProficiencyLevel, error) {
	row := q.db.QueryRow(ctx, createProficiencyLevel,
		arg.ID,
		arg.UserID,
		arg.Value,
		arg.Label,
		arg.Rank,
		arg.Aliases,
		arg.Source,
		arg.SortOrder,
	)
	var i ProficiencyLevel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Value,
		&i.Label,
		&i.Rank,
		&i.Aliases,
		&i.Source,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCareerLevelsByUser = `-- name: ListCareerLevelsByUser :many
SELECT id, user_id, value, label, rank, aliases, length_budget, framing_guidance, is_fallback, source, sort_order, created_at, updated_at FROM career_levels
WHERE user_id = $1
ORDER BY rank, value
`

// The user's seniority ladder, weakest first.
//
// One query serves three readers: the length budget and the framing guidance
// the 2a prompt is given, and the enum the extraction prompt is told to choose
// a posting's seniority from. They read the same rows on purpose -- the six
// hand-synced copies this table replaced had already drifted apart, leaving
// three levels that the database accepted and extraction could never emit.
func (q *Queries) ListCareerLevelsByUser(ctx context.Context, userID uuid.UUID) ([]CareerLevel, error) {
	rows, err := q.db.Query(ctx, listCareerLevelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareerLevel
	for rows.Next() {
		var i CareerLevel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Value,
			&i.Label,
			&i.Rank,
			&i.Aliases,
			&i.LengthBudget,
			&i.FramingGuidance,
			&i.IsFallback,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProficiencyLevelsByUser = `-- name: ListProficiencyLevelsByUser :many
SELECT id, user_id, value, label, rank, aliases, source, sort_order, created_at, updated_at FROM proficiency_levels
WHERE user_id = $1
ORDER BY rank, value
`

// The user's depth scale, weakest first. Read by the fit gate to compare a
// skill's recorded proficiency against the depth a posting asked for.
func (q *Queries) ListProficiencyLevelsByUser(ctx context.Context, userID uuid.UUID) ([]ProficiencyLevel, error) {
	rows, err := q.db.Query(ctx, listProficiencyLevelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProficiencyLevel
	for rows.Next() {
		var i ProficiencyLevel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Value,
			&i.Label,
			&i.Rank,
			&i.Aliases,
			&i.Source,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
