// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	CompanyName string           `json:"company_name"`
	RoleTitle   string           `json:"role_title"`
	JdUrl       *string          `json:"jd_url"`
	JdText      *string          `json:"jd_text"`
	JdSignals   *json.RawMessage `json:"jd_signals"`
	Status      string           `json:"status"`
	AppliedOn   pgtype.Date      `json:"applied_on"`
	Notes       *string          `json:"notes"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type Contribution struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	PositionID      uuid.UUID `json:"position_id"`
	Summary         string    `json:"summary"`
	FullDescription string    `json:"full_description"`
	Outcomes        *string   `json:"outcomes"`
	ScaleContext    *string   `json:"scale_context"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type ContributionFeedback struct {
	ID              uuid.UUID        `json:"id"`
	UserID          uuid.UUID        `json:"user_id"`
	ContributionID  uuid.UUID        `json:"contribution_id"`
	ResumeVersionID uuid.UUID        `json:"resume_version_id"`
	AcceptedBullets []string         `json:"accepted_bullets"`
	RejectedBullets []string         `json:"rejected_bullets"`
	EditedDeltas    *json.RawMessage `json:"edited_deltas"`
	Notes           *string          `json:"notes"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type ContributionTag struct {
	ContributionID uuid.UUID `json:"contribution_id"`
	TagID          uuid.UUID `json:"tag_id"`
}

type Credential struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Name          string      `json:"name"`
	Issuer        *string     `json:"issuer"`
	IssuedOn      pgtype.Date `json:"issued_on"`
	ExpiresOn     pgtype.Date `json:"expires_on"`
	CredentialUrl *string     `json:"credential_url"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type CredentialTag struct {
	CredentialID uuid.UUID `json:"credential_id"`
	TagID        uuid.UUID `json:"tag_id"`
}

type Education struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	Institution  string      `json:"institution"`
	Degree       *string     `json:"degree"`
	FieldOfStudy *string     `json:"field_of_study"`
	StartedOn    pgtype.Date `json:"started_on"`
	EndedOn      pgtype.Date `json:"ended_on"`
	Notes        *string     `json:"notes"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type EducationTag struct {
	EducationID uuid.UUID `json:"education_id"`
	TagID       uuid.UUID `json:"tag_id"`
}

type Employer struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Industry  *string   `json:"industry"`
	Notes     *string   `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Position struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	EmployerID       uuid.UUID   `json:"employer_id"`
	Title            string      `json:"title"`
	IndustryLevel    *string     `json:"industry_level"`
	IndustryRole     *string     `json:"industry_role"`
	LevelRationale   *string     `json:"level_rationale"`
	StartedOn        pgtype.Date `json:"started_on"`
	EndedOn          pgtype.Date `json:"ended_on"`
	ContextNarrative *string     `json:"context_narrative"`
	SortOrder        int32       `json:"sort_order"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Location         *string     `json:"location"`
}

type Preference struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	PreferenceType string    `json:"preference_type"`
	Label          string    `json:"label"`
	Sentiment      string    `json:"sentiment"`
	Weight         *int16    `json:"weight"`
	ContextType    *string   `json:"context_type"`
	Notes          *string   `json:"notes"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	Name         string      `json:"name"`
	Tagline      *string     `json:"tagline"`
	Role         string      `json:"role"`
	Status       string      `json:"status"`
	StartedOn    pgtype.Date `json:"started_on"`
	EndedOn      pgtype.Date `json:"ended_on"`
	RepoUrl      *string     `json:"repo_url"`
	LiveUrl      *string     `json:"live_url"`
	WriteupUrl   *string     `json:"writeup_url"`
	ForceInclude bool        `json:"force_include"`
	ForceExclude bool        `json:"force_exclude"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type ProjectContribution struct {
	ContributionID uuid.UUID `json:"contribution_id"`
	ProjectID      uuid.UUID `json:"project_id"`
}

type ProjectTag struct {
	ProjectID uuid.UUID `json:"project_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

type ResumeVersion struct {
	ID               uuid.UUID        `json:"id"`
	UserID           uuid.UUID        `json:"user_id"`
	ApplicationID    uuid.UUID        `json:"application_id"`
	VersionNumber    int32            `json:"version_number"`
	GenerationParams *json.RawMessage `json:"generation_params"`
	StructuredOutput *json.RawMessage `json:"structured_output"`
	GenerationNotes  *string          `json:"generation_notes"`
	Submitted        bool             `json:"submitted"`
	CreatedAt        time.Time        `json:"created_at"`
}

type Skill struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	TagID           uuid.UUID      `json:"tag_id"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Aliases   []string  `json:"aliases"`
	Category  string    `json:"category"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type TagCategory struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	FullName     *string   `json:"full_name"`
	Phone        *string   `json:"phone"`
	Location     *string   `json:"location"`
	LinkedinUrl  *string   `json:"linkedin_url"`
	GithubUrl    *string   `json:"github_url"`
	SiteUrl      *string   `json:"site_url"`
	Headline     *string   `json:"headline"`
	PasswordHash *string   `json:"password_hash"`
}

type VSkillProvenance struct {
	SkillID        uuid.UUID `json:"skill_id"`
	UserID         uuid.UUID `json:"user_id"`
	ContributionID uuid.UUID `json:"contribution_id"`
}
