// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPosition = `-- name: GetPosition :one
SELECT id, user_id, employer_id, title, industry_level, industry_role, level_rationale, started_on, ended_on, context_narrative, sort_order, created_at, updated_at, location FROM positions
WHERE id = $1 AND user_id = $2
`

type GetPositionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.ID, arg.UserID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployerID,
		&i.Title,
		&i.IndustryLevel,
		&i.IndustryRole,
		&i.LevelRationale,
		&i.StartedOn,
		&i.EndedOn,
		&i.ContextNarrative,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Location,
	)
	return i, err
}

const getPositionsByEmployer = `-- name: GetPositionsByEmployer :many
SELECT id, user_id, employer_id, title, industry_level, industry_role, level_rationale, started_on, ended_on, context_narrative, sort_order, created_at, updated_at, location FROM positions
WHERE employer_id = $1 AND user_id = $2
ORDER BY sort_order, started_on DESC
`

type GetPositionsByEmployerParams struct {
	EmployerID uuid.UUID `json:"employer_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPositionsByEmployer(ctx context.Context, arg GetPositionsByEmployerParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, getPositionsByEmployer, arg.EmployerID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmployerID,
			&i.Title,
			&i.IndustryLevel,
			&i.IndustryRole,
			&i.LevelRationale,
			&i.StartedOn,
			&i.EndedOn,
			&i.ContextNarrative,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
