// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPreference = `-- name: CreatePreference :one
INSERT INTO preferences (id, user_id, preference_type, label, sentiment, weight, is_hard_gate, context_type, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate
`

type CreatePreferenceParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	PreferenceType string    `json:"preference_type"`
	Label          string    `json:"label"`
	Sentiment      string    `json:"sentiment"`
	Weight         int16     `json:"weight"`
	IsHardGate     bool      `json:"is_hard_gate"`
	ContextType    *string   `json:"context_type"`
	Notes          *string   `json:"notes"`
}

func (q *Queries) CreatePreference(ctx context.Context, arg CreatePreferenceParams) (Preference, error) {
	row := q.db.QueryRow(ctx, createPreference,
		arg.ID,
		arg.UserID,
		arg.PreferenceType,
		arg.Label,
		arg.Sentiment,
		arg.Weight,
		arg.IsHardGate,
		arg.ContextType,
		arg.Notes,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferenceType,
		&i.Label,
		&i.Sentiment,
		&i.Weight,
		&i.ContextType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsHardGate,
	)
	return i, err
}

const deletePreference = `-- name: DeletePreference :exec
DELETE FROM preferences
WHERE id = $1 AND user_id = $2
`

type DeletePreferenceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePreference(ctx context.Context, arg DeletePreferenceParams) error {
	_, err := q.db.Exec(ctx, deletePreference, arg.ID, arg.UserID)
	return err
}

const getPreference = `-- name: GetPreference :one
SELECT id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate FROM preferences
WHERE id = $1 AND user_id = $2
`

type GetPreferenceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPreference(ctx context.Context, arg GetPreferenceParams) (Preference, error) {
	row := q.db.QueryRow(ctx, getPreference, arg.ID, arg.UserID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferenceType,
		&i.Label,
		&i.Sentiment,
		&i.Weight,
		&i.ContextType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsHardGate,
	)
	return i, err
}

const listHardGatesByUser = `-- name: ListHardGatesByUser :many
SELECT id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate FROM preferences
WHERE user_id = $1 AND is_hard_gate
ORDER BY preference_type, created_at
`

func (q *Queries) ListHardGatesByUser(ctx context.Context, userID uuid.UUID) ([]Preference, error) {
	rows, err := q.db.Query(ctx, listHardGatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preference
	for rows.Next() {
		var i Preference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PreferenceType,
			&i.Label,
			&i.Sentiment,
			&i.Weight,
			&i.ContextType,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsHardGate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferencesByUser = `-- name: ListPreferencesByUser :many
SELECT id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate FROM preferences
WHERE user_id = $1
ORDER BY preference_type, created_at
`

func (q *Queries) ListPreferencesByUser(ctx context.Context, userID uuid.UUID) ([]Preference, error) {
	rows, err := q.db.Query(ctx, listPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preference
	for rows.Next() {
		var i Preference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PreferenceType,
			&i.Label,
			&i.Sentiment,
			&i.Weight,
			&i.ContextType,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsHardGate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferencesByUserAndType = `-- name: ListPreferencesByUserAndType :many
SELECT id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate FROM preferences
WHERE user_id = $1 AND preference_type = $2
ORDER BY created_at
`

type ListPreferencesByUserAndTypeParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PreferenceType string    `json:"preference_type"`
}

func (q *Queries) ListPreferencesByUserAndType(ctx context.Context, arg ListPreferencesByUserAndTypeParams) ([]Preference, error) {
	rows, err := q.db.Query(ctx, listPreferencesByUserAndType, arg.UserID, arg.PreferenceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Preference
	for rows.Next() {
		var i Preference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PreferenceType,
			&i.Label,
			&i.Sentiment,
			&i.Weight,
			&i.ContextType,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsHardGate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreference = `-- name: UpdatePreference :one
UPDATE preferences
SET preference_type = $3,
    label           = $4,
    sentiment       = $5,
    weight          = $6,
    is_hard_gate    = $7,
    context_type    = $8,
    notes           = $9,
    updated_at      = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, preference_type, label, sentiment, weight, context_type, notes, created_at, updated_at, is_hard_gate
`

type UpdatePreferenceParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	PreferenceType string    `json:"preference_type"`
	Label          string    `json:"label"`
	Sentiment      string    `json:"sentiment"`
	Weight         int16     `json:"weight"`
	IsHardGate     bool      `json:"is_hard_gate"`
	ContextType    *string   `json:"context_type"`
	Notes          *string   `json:"notes"`
}

func (q *Queries) UpdatePreference(ctx context.Context, arg UpdatePreferenceParams) (Preference, error) {
	row := q.db.QueryRow(ctx, updatePreference,
		arg.ID,
		arg.UserID,
		arg.PreferenceType,
		arg.Label,
		arg.Sentiment,
		arg.Weight,
		arg.IsHardGate,
		arg.ContextType,
		arg.Notes,
	)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferenceType,
		&i.Label,
		&i.Sentiment,
		&i.Weight,
		&i.ContextType,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsHardGate,
	)
	return i, err
}
