// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getContributionsByProject = `-- name: GetContributionsByProject :many
SELECT c.id, c.user_id, c.position_id, c.summary, c.full_description, c.outcomes, c.scale_context, c.is_active, c.created_at, c.updated_at FROM contributions c
JOIN project_contributions pc ON pc.contribution_id = c.id
WHERE pc.project_id = $1 AND c.user_id = $2 AND c.is_active = true
ORDER BY c.created_at
`

type GetContributionsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContributionsByProject(ctx context.Context, arg GetContributionsByProjectParams) ([]Contribution, error) {
	rows, err := q.db.Query(ctx, getContributionsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contribution
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PositionID,
			&i.Summary,
			&i.FullDescription,
			&i.Outcomes,
			&i.ScaleContext,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjects = `-- name: GetProjects :many
SELECT id, user_id, name, tagline, role, status, started_on, ended_on, repo_url, live_url, writeup_url, force_include, force_exclude, created_at, updated_at FROM projects
WHERE user_id = $1
ORDER BY started_on DESC NULLS FIRST
`

func (q *Queries) GetProjects(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Tagline,
			&i.Role,
			&i.Status,
			&i.StartedOn,
			&i.EndedOn,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.WriteupUrl,
			&i.ForceInclude,
			&i.ForceExclude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByProject = `-- name: GetTagsByProject :many
SELECT t.id, t.name, t.category, t.sort_order
FROM tags t
JOIN project_tags pt ON pt.tag_id = t.id
WHERE pt.project_id = $1 AND t.user_id = $2
ORDER BY t.sort_order, t.name
`

type GetTagsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetTagsByProjectRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) GetTagsByProject(ctx context.Context, arg GetTagsByProjectParams) ([]GetTagsByProjectRow, error) {
	rows, err := q.db.Query(ctx, getTagsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByProjectRow
	for rows.Next() {
		var i GetTagsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
