// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateResumeVersion(ctx context.Context, arg CreateResumeVersionParams) (ResumeVersion, error)
	GetApplication(ctx context.Context, arg GetApplicationParams) (Application, error)
	GetContribution(ctx context.Context, arg GetContributionParams) (Contribution, error)
	GetContributionsByPosition(ctx context.Context, arg GetContributionsByPositionParams) ([]Contribution, error)
	GetEmployer(ctx context.Context, arg GetEmployerParams) (Employer, error)
	GetEmployers(ctx context.Context, userID uuid.UUID) ([]Employer, error)
	GetPosition(ctx context.Context, arg GetPositionParams) (Position, error)
	GetPositionsByEmployer(ctx context.Context, arg GetPositionsByEmployerParams) ([]Position, error)
	GetTagsByContribution(ctx context.Context, arg GetTagsByContributionParams) ([]GetTagsByContributionRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListApplications(ctx context.Context, userID uuid.UUID) ([]Application, error)
	NextResumeVersionNumber(ctx context.Context, arg NextResumeVersionNumberParams) (int32, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	UpdateApplicationSignals(ctx context.Context, arg UpdateApplicationSignalsParams) (Application, error)
}

var _ Querier = (*Queries)(nil)
