// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateResumeVersion(ctx context.Context, arg CreateResumeVersionParams) (ResumeVersion, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetApplication(ctx context.Context, arg GetApplicationParams) (Application, error)
	GetContribution(ctx context.Context, arg GetContributionParams) (Contribution, error)
	GetContributionsByPosition(ctx context.Context, arg GetContributionsByPositionParams) ([]Contribution, error)
	GetContributionsByProject(ctx context.Context, arg GetContributionsByProjectParams) ([]Contribution, error)
	GetCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error)
	GetEducation(ctx context.Context, userID uuid.UUID) ([]Education, error)
	GetEmployer(ctx context.Context, arg GetEmployerParams) (Employer, error)
	GetEmployers(ctx context.Context, userID uuid.UUID) ([]Employer, error)
	GetPosition(ctx context.Context, arg GetPositionParams) (Position, error)
	GetPositionsByEmployer(ctx context.Context, arg GetPositionsByEmployerParams) ([]Position, error)
	GetProjects(ctx context.Context, userID uuid.UUID) ([]Project, error)
	GetResumeVersion(ctx context.Context, arg GetResumeVersionParams) (ResumeVersion, error)
	GetTagsByContribution(ctx context.Context, arg GetTagsByContributionParams) ([]GetTagsByContributionRow, error)
	GetTagsByProject(ctx context.Context, arg GetTagsByProjectParams) ([]GetTagsByProjectRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	ListApplications(ctx context.Context, userID uuid.UUID) ([]Application, error)
	ListResumeVersions(ctx context.Context, arg ListResumeVersionsParams) ([]ResumeVersion, error)
	NextResumeVersionNumber(ctx context.Context, arg NextResumeVersionNumberParams) (int32, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	UpdateApplicationSignals(ctx context.Context, arg UpdateApplicationSignalsParams) (Application, error)
}

var _ Querier = (*Queries)(nil)
