// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resume_sections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createResumeSection = `-- name: CreateResumeSection :one
INSERT INTO resume_sections (
    id, user_id, key, heading, sort_order, hidden, source
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, key, heading, sort_order, hidden, source, created_at, updated_at
`

type CreateResumeSectionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Key       string    `json:"key"`
	Heading   string    `json:"heading"`
	SortOrder int32     `json:"sort_order"`
	Hidden    bool      `json:"hidden"`
	Source    string    `json:"source"`
}

func (q *Queries) CreateResumeSection(ctx context.Context, arg CreateResumeSectionParams) (ResumeSection, error) {
	row := q.db.QueryRow(ctx, createResumeSection,
		arg.ID,
		arg.UserID,
		arg.Key,
		arg.Heading,
		arg.SortOrder,
		arg.Hidden,
		arg.Source,
	)
	var i ResumeSection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Heading,
		&i.SortOrder,
		&i.Hidden,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResumeSectionsByUser = `-- name: ListResumeSectionsByUser :many
SELECT id, user_id, key, heading, sort_order, hidden, source, created_at, updated_at FROM resume_sections
WHERE user_id = $1
ORDER BY sort_order, key
`

// The user's section manifest in print order, hidden rows included.
//
// Hidden rows are returned rather than filtered in SQL because the caller is
// what decides they mean nothing to the document; a future settings screen
// wants to list them, and a WHERE clause here would hide them from it too.
func (q *Queries) ListResumeSectionsByUser(ctx context.Context, userID uuid.UUID) ([]ResumeSection, error) {
	rows, err := q.db.Query(ctx, listResumeSectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumeSection
	for rows.Next() {
		var i ResumeSection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Heading,
			&i.SortOrder,
			&i.Hidden,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
