// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resume_versions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createResumeVersion = `-- name: CreateResumeVersion :one
INSERT INTO resume_versions (
    id, user_id, application_id, version_number, generation_params, structured_output
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, application_id, version_number, generation_params, structured_output, generation_notes, submitted, created_at
`

type CreateResumeVersionParams struct {
	ID               uuid.UUID        `json:"id"`
	UserID           uuid.UUID        `json:"user_id"`
	ApplicationID    uuid.UUID        `json:"application_id"`
	VersionNumber    int32            `json:"version_number"`
	GenerationParams *json.RawMessage `json:"generation_params"`
	StructuredOutput *json.RawMessage `json:"structured_output"`
}

func (q *Queries) CreateResumeVersion(ctx context.Context, arg CreateResumeVersionParams) (ResumeVersion, error) {
	row := q.db.QueryRow(ctx, createResumeVersion,
		arg.ID,
		arg.UserID,
		arg.ApplicationID,
		arg.VersionNumber,
		arg.GenerationParams,
		arg.StructuredOutput,
	)
	var i ResumeVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.VersionNumber,
		&i.GenerationParams,
		&i.StructuredOutput,
		&i.GenerationNotes,
		&i.Submitted,
		&i.CreatedAt,
	)
	return i, err
}

const getResumeVersion = `-- name: GetResumeVersion :one
SELECT id, user_id, application_id, version_number, generation_params, structured_output, generation_notes, submitted, created_at FROM resume_versions
WHERE id = $1 AND user_id = $2
`

type GetResumeVersionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetResumeVersion(ctx context.Context, arg GetResumeVersionParams) (ResumeVersion, error) {
	row := q.db.QueryRow(ctx, getResumeVersion, arg.ID, arg.UserID)
	var i ResumeVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicationID,
		&i.VersionNumber,
		&i.GenerationParams,
		&i.StructuredOutput,
		&i.GenerationNotes,
		&i.Submitted,
		&i.CreatedAt,
	)
	return i, err
}

const listResumeVersions = `-- name: ListResumeVersions :many
SELECT id, user_id, application_id, version_number, generation_params, structured_output, generation_notes, submitted, created_at FROM resume_versions
WHERE application_id = $1 AND user_id = $2
ORDER BY version_number DESC
`

type ListResumeVersionsParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) ListResumeVersions(ctx context.Context, arg ListResumeVersionsParams) ([]ResumeVersion, error) {
	rows, err := q.db.Query(ctx, listResumeVersions, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumeVersion
	for rows.Next() {
		var i ResumeVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicationID,
			&i.VersionNumber,
			&i.GenerationParams,
			&i.StructuredOutput,
			&i.GenerationNotes,
			&i.Submitted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextResumeVersionNumber = `-- name: NextResumeVersionNumber :one
SELECT COALESCE(MAX(version_number), 0) + 1
FROM resume_versions
WHERE application_id = $1 AND user_id = $2
`

type NextResumeVersionNumberParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) NextResumeVersionNumber(ctx context.Context, arg NextResumeVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextResumeVersionNumber, arg.ApplicationID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
