// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, user_id, tag_id, proficiency, years_experience, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at
`

type CreateSkillParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	TagID           uuid.UUID      `json:"tag_id"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.UserID,
		arg.TagID,
		arg.Proficiency,
		arg.YearsExperience,
		arg.IsActive,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills
WHERE id = $1 AND user_id = $2
`

type DeleteSkillParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.UserID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE id = $1 AND user_id = $2
`

type GetSkillParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.UserID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSkillTagNamesByUser = `-- name: ListActiveSkillTagNamesByUser :many
SELECT t.name
FROM skills s
JOIN tags t ON t.id = s.tag_id
WHERE s.user_id = $1 AND s.is_active = true
`

func (q *Queries) ListActiveSkillTagNamesByUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveSkillTagNamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSkillsByUser = `-- name: ListActiveSkillsByUser :many
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE user_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveSkillsByUser(ctx context.Context, userID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listActiveSkillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TagID,
			&i.Proficiency,
			&i.YearsExperience,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionsBySkill = `-- name: ListContributionsBySkill :many
SELECT contribution_id FROM v_skill_provenance
WHERE skill_id = $1
`

func (q *Queries) ListContributionsBySkill(ctx context.Context, skillID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listContributionsBySkill, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var contribution_id uuid.UUID
		if err := rows.Scan(&contribution_id); err != nil {
			return nil, err
		}
		items = append(items, contribution_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByUser = `-- name: ListSkillsByUser :many
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListSkillsByUser(ctx context.Context, userID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TagID,
			&i.Proficiency,
			&i.YearsExperience,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET proficiency      = $3,
    years_experience = $4,
    is_active        = $5,
    updated_at       = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at
`

type UpdateSkillParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.UserID,
		arg.Proficiency,
		arg.YearsExperience,
		arg.IsActive,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
