// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, user_id, tag_id, proficiency, years_experience, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at
`

type CreateSkillParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	TagID           uuid.UUID      `json:"tag_id"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.UserID,
		arg.TagID,
		arg.Proficiency,
		arg.YearsExperience,
		arg.IsActive,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills
WHERE id = $1 AND user_id = $2
`

type DeleteSkillParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.UserID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE id = $1 AND user_id = $2
`

type GetSkillParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.UserID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSkillMatchTermsByUser = `-- name: ListActiveSkillMatchTermsByUser :many
SELECT t.name, t.aliases, t.category, c.aliases AS category_aliases, s.proficiency
FROM skills s
JOIN tags t ON t.id = s.tag_id AND t.user_id = s.user_id
JOIN tag_categories c ON c.user_id = t.user_id AND c.name = t.category
WHERE s.user_id = $1 AND s.is_active = true
`

type ListActiveSkillMatchTermsByUserRow struct {
	Name            string   `json:"name"`
	Aliases         []string `json:"aliases"`
	Category        string   `json:"category"`
	CategoryAliases []string `json:"category_aliases"`
	Proficiency     string   `json:"proficiency"`
}

// Everything the fit-gate matcher needs to answer a JD requirement: the
// canonical name, the synonyms a JD might use instead, and the category that
// carries the competency vocabulary a JD phrases requirements in. Selecting
// t.name alone is what made "Golang" a gap against a stored "Go", and
// "CI/CD" a gap against Jenkins.
//
// The join is constrained on user_id as well as tag_id. FK integrity on
// skills.tag_id already implies it; stating it keeps the row set correct if a
// tag is ever re-pointed.
//
// s.proficiency is selected but s.years_experience deliberately is not. The
// scorer compares an ordinal level against a level the JD asked for, and a JD
// states depth as a level far more often than as a number — where it does give
// a figure ("5+ years"), extraction reads it as a level signal rather than
// handing the scorer a number to compare. Selecting years here would put a
// column in front of the matcher with nothing to compare it to.
func (q *Queries) ListActiveSkillMatchTermsByUser(ctx context.Context, userID uuid.UUID) ([]ListActiveSkillMatchTermsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveSkillMatchTermsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSkillMatchTermsByUserRow
	for rows.Next() {
		var i ListActiveSkillMatchTermsByUserRow
		if err := rows.Scan(
			&i.Name,
			&i.Aliases,
			&i.Category,
			&i.CategoryAliases,
			&i.Proficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSkillProfileByUser = `-- name: ListActiveSkillProfileByUser :many
SELECT t.name, t.category, s.proficiency, s.years_experience
FROM skills s
JOIN tags t ON t.id = s.tag_id AND t.user_id = s.user_id
WHERE s.user_id = $1 AND s.is_active = true
ORDER BY t.category, s.years_experience DESC NULLS LAST, t.name
`

type ListActiveSkillProfileByUserRow struct {
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
}

// The claimed skills with their depth signal, for the generation prompt.
//
// Generation previously built the resume's Skills section out of contribution
// tags, which are vocabulary rather than claims: a tag can be attached to a
// contribution without ever being a skill the user asserts, and JavaScript
// reached a rendered resume that way. It also meant proficiency and
// years_experience were dropped at the query layer, so a 25-year expert Java
// and a 2-year novice Python arrived at the prompt indistinguishable.
//
// Ordered category-major, then strongest first within a category, so the
// prompt reads the depth ranking without having to derive it. NULL years sort
// last: an unrecorded duration is not evidence of a short one.
func (q *Queries) ListActiveSkillProfileByUser(ctx context.Context, userID uuid.UUID) ([]ListActiveSkillProfileByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveSkillProfileByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSkillProfileByUserRow
	for rows.Next() {
		var i ListActiveSkillProfileByUserRow
		if err := rows.Scan(
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.YearsExperience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSkillTagNamesByUser = `-- name: ListActiveSkillTagNamesByUser :many
SELECT t.name
FROM skills s
JOIN tags t ON t.id = s.tag_id
WHERE s.user_id = $1 AND s.is_active = true
`

func (q *Queries) ListActiveSkillTagNamesByUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveSkillTagNamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSkillsByUser = `-- name: ListActiveSkillsByUser :many
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE user_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveSkillsByUser(ctx context.Context, userID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listActiveSkillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TagID,
			&i.Proficiency,
			&i.YearsExperience,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionsBySkill = `-- name: ListContributionsBySkill :many
SELECT contribution_id FROM v_skill_provenance
WHERE skill_id = $1
`

func (q *Queries) ListContributionsBySkill(ctx context.Context, skillID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listContributionsBySkill, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var contribution_id uuid.UUID
		if err := rows.Scan(&contribution_id); err != nil {
			return nil, err
		}
		items = append(items, contribution_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByUser = `-- name: ListSkillsByUser :many
SELECT id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at FROM skills
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListSkillsByUser(ctx context.Context, userID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TagID,
			&i.Proficiency,
			&i.YearsExperience,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET proficiency      = $3,
    years_experience = $4,
    is_active        = $5,
    updated_at       = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, tag_id, proficiency, years_experience, is_active, created_at, updated_at
`

type UpdateSkillParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Proficiency     string         `json:"proficiency"`
	YearsExperience pgtype.Numeric `json:"years_experience"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.UserID,
		arg.Proficiency,
		arg.YearsExperience,
		arg.IsActive,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TagID,
		&i.Proficiency,
		&i.YearsExperience,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
