// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTagsByContribution = `-- name: GetTagsByContribution :many
SELECT t.id, t.name, t.category, t.sort_order
FROM tags t
JOIN contribution_tags ct ON ct.tag_id = t.id
WHERE ct.contribution_id = $1 AND t.user_id = $2
ORDER BY t.sort_order, t.name
`

type GetTagsByContributionParams struct {
	ContributionID uuid.UUID `json:"contribution_id"`
	UserID         uuid.UUID `json:"user_id"`
}

type GetTagsByContributionRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) GetTagsByContribution(ctx context.Context, arg GetTagsByContributionParams) ([]GetTagsByContributionRow, error) {
	rows, err := q.db.Query(ctx, getTagsByContribution, arg.ContributionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByContributionRow
	for rows.Next() {
		var i GetTagsByContributionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
