// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, email, created_at, updated_at, full_name, phone, location, linkedin_url, github_url, site_url, headline FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.Phone,
		&i.Location,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.SiteUrl,
		&i.Headline,
	)
	return i, err
}
